### ISSUE TITLE
No recipe for compact machines

### ISSUE THREAD

**Issue by winkeyface14** [robotgryphon/compact-machines#11]
Compact Machines version: 4.0.0-alpha.5
Forge version: 35.1.13

Based on the changelog for alpha 5, vanilla recipes are enabled by default. I created a world and there are no recipes for any of the machines. I tried to put the datapack of recipes and reloaded the world and then the recipes showed up. I assume that you don't need the data pack since the mod already has it by default.

**Comment by robotgryphon** [comment]
This was an issue with the generated recipe files not being included in the repository; I've added them and built a new release, alpha 6. It should be on Curseforge shortly, or you can grab it on the releases page here.

Thanks for the report!
