### ISSUE TITLE
Didnt know where to ask this question, but will we eventually see this on curseforge one day?

### ISSUE THREAD

**Issue by Scapulaunit12** [robotgryphon/compact-machines#9]
Title

**Comment by Codingale** [comment]
So I asked about it here: https://github.com/robotgryphon/compact-machines/commit/8c6b933bd3772b929803f973d8ccf8ff28750429#commitcomment-43526397

And they said that the version is currently unstable, no recipes exist, and tunnels are not implemented, as far as I can tell it's just them working on it in their off time, so it's possible but, hard to tell if they can or what curseforge will be doing in the near future about updates to mods, granted I have seen ExtremeReactors/BigReactors etc updated on curseforge so if licenses permit it, it might be **but**,
I don't know much just speculation.

**Comment by Scapulaunit12** [comment]
ah yeah, I dont really care when it happens im very patient when it comes to mods just wanted to know if it was possible.

**Comment by robotgryphon** [comment]
Alpha 3 and Alpha 4 are both being uploaded to CurseForge now. Just got the final permissions to update the original project. Brace yourselves!
